#!/usr/bin/bash


#options
#-c
#-tile
#-slow
#-segfa
#-1d
declare -a options=("-help" "-tile" "-slow" "-segfa" "-1d" "-optim")
Compile_tile()
{
	runname="runtile"

	if test -f $runname;then
    rm $runname
fi
echo "---Tile-------" 
clang -I ../../Smart_Stopper maintile.c  -o $runname -Wall -fopenmp=libomp -Ofast -gline-tables-only -lm -fopenmp-version=51 -Rpass-analysis=loop-vectorize -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -march=native 
echo "---end compiling----"
}
Compile_slow()
{

	runname="runslow"

	if test -f $runname;then
    rm $runname
fi
echo "---$runname-------" 
clang  mainslow.c  -o $runname -Wall -fopenmp=libomp -O3 -fast -lm -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target -march=sm_70 -gline-tables-only #-D NO_TIME
echo "---end compiling----"
}


Compile_1d()
{

	runname="run1d"

	if test -f $runname;then
    rm $runname
fi
echo "---$runname-------" 
clang -I ../../Smart_Stopper main1d.c  -o $runname -Wall -fopenmp=libomp -O3 -fast -lm -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target -march=sm_70 -gline-tables-only -fopenmp-version=51 #-D NO_TIME
echo "---end compiling----"
}


Compile_optim()
{
	echo $1 $2
	runname="runoptim"

	if test -f $runname;then
    rm $runname
fi
echo "---$runname-------" 
if [[ "$1" == "LOMP" ]];then
echo "omp"
clang -I ../../Smart_Stopper mainoptim.c  -o $runname -Wall -fopenmp=libomp -O3 -fast -lm -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target -march=sm_70 -gline-tables-only -D $1 -D $2 #-D L1D #-fopenmp-version=51 #-D NO_TIME
else
echo "acc"
pgcc -acc -Minfo=accel -ta=tesla -Wall -I ../../Smart_Stopper -c99 mainoptim.c -o $runname -D LACC -D $2
fi
echo "---end compiling----"
}




echo "Compiling script"



if (($#==0)) ;then
echo "No input argument."
exit 1
fi
IFS=' ' read -r -a tomb <<< $@

for ((i=0;i<$#;i++));do
case ${tomb[$i]} in 
		-tile)
			Compile_tile
			;;
		-segfa)
			Compile_segfa 
			;;
		-slow)
			Compile_slow
			;;
		-help)
			for i in "${options[@]}"
				do
				echo "$i"
				done
			;;
		-1d)
			Compile_1d
			;;
		-optim)
			Compile_optim  ${tomb[$i+1]} ${tomb[$i+2]}
			i+=2
			;;

esac
done


#echo "compile for any? gpu..." 
#clang -I ../../Smart_Stopper mainbase.c  -o run -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -D LOMP

#clang -I ../../Smart_Stopper mainbase.c  -o run_v100 -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -Xopenmp-target -march=sm_70 -D LOMP

#pgcc -acc -Minfo=accel -ta=tesla -Wall -I ../../Smart_Stopper -c99 mainbase.c -o runacc -D LACC
