#!/usr/bin/bash



Compile_openmp()
{
mode=$1
#echo $1
    if [[ "$mode" == "k80" ]];then
        if test -f run;then
            rm run_k80
        fi

        echo "---k80 or any gpu---" 
        clang -I ../../Smart_Stopper mainbase.c  -o run_k80 -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -D LOMP 
        echo "---end compiling----"

    fi
    if [[ "$mode" == "v100" ]];then
        if test -f run_v100;then
            rm run_v100
        fi
        echo "---tesla v100-------" 
        clang -I ../../Smart_Stopper mainbase.c  -o run_v100 -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -Xopenmp-target -march=sm_70 -D LOMP
        echo "---end compiling----"
    fi
} 

Compile_openacc()
{
    if test -f runacc;then
        rm runacc
    fi
    echo "---Acc ----------" 
    pgcc -acc -Minfo=accel -ta=tesla -Wall -I ../../Smart_Stopper -c99 mainbase.c -o runacc -D LACC
    echo "---end compiling-"
}

Compile_cpu()
{
    echo "CPU compiling is not yet implemented in this script"
}



echo "Compiling script"



if (($#==0)) ;then
Compile_openmp "k80"
Compile_openmp "v100"
Compile_openacc
fi
IFS=' ' read -r -a tomb <<< $@

for ((i=0;i<$#;i++));do
case ${tomb[$i]} in 
		-omp)
			Compile_openmp ${tomb[($i+1)]}
			((i++))
			;;
		-acc)
			Compile_openacc 
			;;
		-cpu)
			Compile_cpu
			;;

esac
done





#if test -f runser;then
#    rm runser
#fi


#echo "compile for any? gpu..." 
#clang -I ../../Smart_Stopper main.c  -o run -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm 
#echo "compile for titan v100.."
#clang -I ../../Smart_Stopper main.c  -o run_v100 -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -Xopenmp-target -march=sm_70 
#-Xarch_device sm_70

#pgcc -omp -I ../../Smart_Stopper main.c  -o run -Wall -fopenmp=libomp -lm 


#echo "compile serial"
#clang -I ../../Smart_Stopper serialmain.c  -o runser -Wall -Ofast -gline-tables-only -lm




#echo "compile for any? gpu..." 
#clang -I ../../Smart_Stopper mainbase.c  -o run -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -D LOMP

#clang -I ../../Smart_Stopper mainbase.c  -o run_v100 -Wall -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Ofast -gline-tables-only -lm -Xopenmp-target -march=sm_70 -D LOMP

#pgcc -acc -Minfo=accel -ta=tesla -Wall -I ../../Smart_Stopper -c99 mainbase.c -o runacc -D LACC
